export const masterDataPaths = {
  '/companies': {
    post: {
      summary: 'Create Company Profile',
      tags: ['Companies'],
      security: [{ bearerAuth: [] }],
      requestBody: {
        required: true,
        content: {
          'application/json': {
            schema: {
              type: 'object',
              required: ['name', 'legalName', 'gstNumber', 'panNumber'],
              properties: {
                name: { type: 'string', example: 'GoldCraft Jewellers Pvt Ltd' },
                legalName: { type: 'string', example: 'GoldCraft Private Limited' },
                gstNumber: { type: 'string', example: '07AAAAA1111A1Z5' },
                panNumber: { type: 'string', example: 'AAAAA1111A' },
                email: { type: 'string', example: 'info@goldcraft.com' },
                phone: { type: 'string', example: '9876543210' },
                website: { type: 'string', example: 'https://goldcraft.com' },
                logoUrl: { type: 'string', example: 'https://goldcraft.com/logo.png' },
                isActive: { type: 'boolean', example: true },
              },
            },
          },
        },
      },
      responses: {
        201: { description: 'Company created successfully' },
        400: { description: 'Validation error' },
        401: { description: 'Unauthorized' },
        403: { description: 'Forbidden' },
        409: { description: 'Duplicate GSTIN / PAN / Code' },
      },
    },
    get: {
      summary: 'List Companies (Search, Status Filter, Sorting & Pagination)',
      tags: ['Companies'],
      security: [{ bearerAuth: [] }],
      parameters: [
        { name: 'search', in: 'query', schema: { type: 'string' }, description: 'Keyword search across name, legalName, GSTIN, PAN, email, phone' },
        { name: 'isActive', in: 'query', schema: { type: 'boolean' }, description: 'Filter by active status' },
        { name: 'sortBy', in: 'query', schema: { type: 'string', enum: ['createdAt', 'name', 'legalName', 'gstNumber', 'panNumber'] } },
        { name: 'sortOrder', in: 'query', schema: { type: 'string', enum: ['asc', 'desc'] } },
        { name: 'page', in: 'query', schema: { type: 'integer', default: 1 } },
        { name: 'limit', in: 'query', schema: { type: 'integer', default: 10 } },
      ],
      responses: {
        200: { description: 'Company list retrieved successfully' },
        401: { description: 'Unauthorized' },
        403: { description: 'Forbidden' },
      },
    },
  },
  '/companies/{id}': {
    get: {
      summary: 'Get Company by ID',
      tags: ['Companies'],
      security: [{ bearerAuth: [] }],
      parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
      responses: {
        200: { description: 'Company profile retrieved successfully' },
        404: { description: 'Company not found' },
      },
    },
    put: {
      summary: 'Update Company Profile',
      tags: ['Companies'],
      security: [{ bearerAuth: [] }],
      parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
      responses: {
        200: { description: 'Company updated successfully' },
        404: { description: 'Company not found' },
        409: { description: 'Duplicate GSTIN / PAN' },
      },
    },
    delete: {
      summary: 'Delete Company Profile',
      tags: ['Companies'],
      security: [{ bearerAuth: [] }],
      parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
      responses: {
        200: { description: 'Company deleted successfully' },
        404: { description: 'Company not found' },
      },
    },
  },
  '/branches': {
    post: {
      summary: 'Create Branch Profile',
      tags: ['Branches'],
      security: [{ bearerAuth: [] }],
      responses: { 201: { description: 'Branch created' } },
    },
    get: {
      summary: 'List Branches (Search, Company, City & Sort)',
      tags: ['Branches'],
      security: [{ bearerAuth: [] }],
      parameters: [
        { name: 'companyId', in: 'query', schema: { type: 'string', format: 'uuid' } },
        { name: 'city', in: 'query', schema: { type: 'string' } },
        { name: 'search', in: 'query', schema: { type: 'string' } },
        { name: 'isActive', in: 'query', schema: { type: 'boolean' } },
        { name: 'sortBy', in: 'query', schema: { type: 'string', enum: ['createdAt', 'name', 'branchCode', 'city'] } },
        { name: 'sortOrder', in: 'query', schema: { type: 'string', enum: ['asc', 'desc'] } },
        { name: 'page', in: 'query', schema: { type: 'integer', default: 1 } },
        { name: 'limit', in: 'query', schema: { type: 'integer', default: 10 } },
      ],
      responses: { 200: { description: 'Branch list retrieved' } },
    },
  },
  '/branches/{id}': {
    get: { summary: 'Get Branch by ID', tags: ['Branches'], security: [{ bearerAuth: [] }], responses: { 200: { description: 'Success' } } },
    put: { summary: 'Update Branch', tags: ['Branches'], security: [{ bearerAuth: [] }], responses: { 200: { description: 'Success' } } },
    delete: { summary: 'Delete Branch', tags: ['Branches'], security: [{ bearerAuth: [] }], responses: { 200: { description: 'Success' } } },
  },
  '/employees': {
    post: { summary: 'Create Employee', tags: ['Employees'], security: [{ bearerAuth: [] }], responses: { 201: { description: 'Created' } } },
    get: {
      summary: 'List Employees (Search, Company, Branch, Designation & Sort)',
      tags: ['Employees'],
      security: [{ bearerAuth: [] }],
      parameters: [
        { name: 'companyId', in: 'query', schema: { type: 'string', format: 'uuid' }, description: 'Filter by Company ID (via branch)' },
        { name: 'branchId', in: 'query', schema: { type: 'string', format: 'uuid' } },
        { name: 'designation', in: 'query', schema: { type: 'string' } },
        { name: 'search', in: 'query', schema: { type: 'string' } },
        { name: 'isActive', in: 'query', schema: { type: 'boolean' } },
        { name: 'sortBy', in: 'query', schema: { type: 'string', enum: ['createdAt', 'employeeCode', 'firstName', 'lastName', 'designation'] } },
        { name: 'sortOrder', in: 'query', schema: { type: 'string', enum: ['asc', 'desc'] } },
        { name: 'page', in: 'query', schema: { type: 'integer', default: 1 } },
        { name: 'limit', in: 'query', schema: { type: 'integer', default: 10 } },
      ],
      responses: { 200: { description: 'Success' } },
    },
  },
  '/employees/{id}': {
    get: { summary: 'Get Employee by ID', tags: ['Employees'], security: [{ bearerAuth: [] }], responses: { 200: { description: 'Success' } } },
    put: { summary: 'Update Employee', tags: ['Employees'], security: [{ bearerAuth: [] }], responses: { 200: { description: 'Success' } } },
    delete: { summary: 'Delete Employee', tags: ['Employees'], security: [{ bearerAuth: [] }], responses: { 200: { description: 'Success' } } },
  },
  '/customers/search': {
    get: {
      summary: 'Fast POS Customer Quick Search',
      tags: ['Customers'],
      security: [{ bearerAuth: [] }],
      parameters: [{ name: 'q', in: 'query', required: true, schema: { type: 'string' }, description: 'Quick search term (mobile, customerCode, name)' }],
      responses: { 200: { description: 'Matching customers list' } },
    },
  },
  '/customers': {
    post: { summary: 'Create Customer', tags: ['Customers'], security: [{ bearerAuth: [] }], responses: { 201: { description: 'Created' } } },
    get: {
      summary: 'List Customers (Search, Company, Branch, CustomerType & Sort)',
      tags: ['Customers'],
      security: [{ bearerAuth: [] }],
      parameters: [
        { name: 'companyId', in: 'query', schema: { type: 'string', format: 'uuid' }, description: 'Filter by Company ID (via branch)' },
        { name: 'branchId', in: 'query', schema: { type: 'string', format: 'uuid' } },
        { name: 'customerType', in: 'query', schema: { type: 'string' } },
        { name: 'search', in: 'query', schema: { type: 'string' } },
        { name: 'isActive', in: 'query', schema: { type: 'boolean' } },
        { name: 'sortBy', in: 'query', schema: { type: 'string', enum: ['createdAt', 'customerCode', 'firstName', 'lastName'] } },
        { name: 'sortOrder', in: 'query', schema: { type: 'string', enum: ['asc', 'desc'] } },
        { name: 'page', in: 'query', schema: { type: 'integer', default: 1 } },
        { name: 'limit', in: 'query', schema: { type: 'integer', default: 10 } },
      ],
      responses: { 200: { description: 'Success' } },
    },
  },
  '/customers/{id}': {
    get: { summary: 'Get Customer by ID', tags: ['Customers'], security: [{ bearerAuth: [] }], responses: { 200: { description: 'Success' } } },
    put: { summary: 'Update Customer', tags: ['Customers'], security: [{ bearerAuth: [] }], responses: { 200: { description: 'Success' } } },
    delete: { summary: 'Delete Customer', tags: ['Customers'], security: [{ bearerAuth: [] }], responses: { 200: { description: 'Success' } } },
  },
  '/vendors': {
    post: { summary: 'Create Vendor', tags: ['Vendors'], security: [{ bearerAuth: [] }], responses: { 201: { description: 'Created' } } },
    get: {
      summary: 'List Vendors (Search, GSTIN & Sort)',
      tags: ['Vendors'],
      security: [{ bearerAuth: [] }],
      parameters: [
        { name: 'branchId', in: 'query', schema: { type: 'string', format: 'uuid' } },
        { name: 'gstNumber', in: 'query', schema: { type: 'string' } },
        { name: 'search', in: 'query', schema: { type: 'string' } },
        { name: 'isActive', in: 'query', schema: { type: 'boolean' } },
        { name: 'sortBy', in: 'query', schema: { type: 'string', enum: ['createdAt', 'vendorCode', 'companyName', 'contactPerson'] } },
        { name: 'sortOrder', in: 'query', schema: { type: 'string', enum: ['asc', 'desc'] } },
        { name: 'page', in: 'query', schema: { type: 'integer', default: 1 } },
        { name: 'limit', in: 'query', schema: { type: 'integer', default: 10 } },
      ],
      responses: { 200: { description: 'Success' } },
    },
  },
  '/vendors/{id}': {
    get: { summary: 'Get Vendor by ID', tags: ['Vendors'], security: [{ bearerAuth: [] }], responses: { 200: { description: 'Success' } } },
    put: { summary: 'Update Vendor', tags: ['Vendors'], security: [{ bearerAuth: [] }], responses: { 200: { description: 'Success' } } },
    delete: { summary: 'Delete Vendor', tags: ['Vendors'], security: [{ bearerAuth: [] }], responses: { 200: { description: 'Success' } } },
  },
  '/product-categories': {
    post: { summary: 'Create Product Category', tags: ['Product Categories'], security: [{ bearerAuth: [] }], responses: { 201: { description: 'Created' } } },
    get: {
      summary: 'List Product Categories (Search & Sort)',
      tags: ['Product Categories'],
      security: [{ bearerAuth: [] }],
      parameters: [
        { name: 'search', in: 'query', schema: { type: 'string' } },
        { name: 'isActive', in: 'query', schema: { type: 'boolean' } },
        { name: 'sortBy', in: 'query', schema: { type: 'string', enum: ['createdAt', 'name', 'code'] } },
        { name: 'sortOrder', in: 'query', schema: { type: 'string', enum: ['asc', 'desc'] } },
        { name: 'page', in: 'query', schema: { type: 'integer', default: 1 } },
        { name: 'limit', in: 'query', schema: { type: 'integer', default: 10 } },
      ],
      responses: { 200: { description: 'Success' } },
    },
  },
  '/product-categories/{id}': {
    get: { summary: 'Get Category by ID', tags: ['Product Categories'], security: [{ bearerAuth: [] }], responses: { 200: { description: 'Success' } } },
    put: { summary: 'Update Category', tags: ['Product Categories'], security: [{ bearerAuth: [] }], responses: { 200: { description: 'Success' } } },
    delete: { summary: 'Delete Category', tags: ['Product Categories'], security: [{ bearerAuth: [] }], responses: { 200: { description: 'Success' } } },
  },
  '/product-sub-categories': {
    post: { summary: 'Create Product Sub-Category', tags: ['Product Sub-Categories'], security: [{ bearerAuth: [] }], responses: { 201: { description: 'Created' } } },
    get: {
      summary: 'List Product Sub-Categories (Search, Category & Sort)',
      tags: ['Product Sub-Categories'],
      security: [{ bearerAuth: [] }],
      parameters: [
        { name: 'categoryId', in: 'query', schema: { type: 'string', format: 'uuid' } },
        { name: 'search', in: 'query', schema: { type: 'string' } },
        { name: 'isActive', in: 'query', schema: { type: 'boolean' } },
        { name: 'sortBy', in: 'query', schema: { type: 'string', enum: ['createdAt', 'name', 'code'] } },
        { name: 'sortOrder', in: 'query', schema: { type: 'string', enum: ['asc', 'desc'] } },
        { name: 'page', in: 'query', schema: { type: 'integer', default: 1 } },
        { name: 'limit', in: 'query', schema: { type: 'integer', default: 10 } },
      ],
      responses: { 200: { description: 'Success' } },
    },
  },
  '/product-sub-categories/{id}': {
    get: { summary: 'Get Sub-Category by ID', tags: ['Product Sub-Categories'], security: [{ bearerAuth: [] }], responses: { 200: { description: 'Success' } } },
    put: { summary: 'Update Sub-Category', tags: ['Product Sub-Categories'], security: [{ bearerAuth: [] }], responses: { 200: { description: 'Success' } } },
    delete: { summary: 'Delete Sub-Category', tags: ['Product Sub-Categories'], security: [{ bearerAuth: [] }], responses: { 200: { description: 'Success' } } },
  },
  '/products': {
    post: { summary: 'Create Product', tags: ['Products'], security: [{ bearerAuth: [] }], responses: { 201: { description: 'Created' } } },
    get: {
      summary: 'List Products (Search, Category, SubCategory, MetalType & Sort)',
      tags: ['Products'],
      security: [{ bearerAuth: [] }],
      parameters: [
        { name: 'categoryId', in: 'query', schema: { type: 'string', format: 'uuid' }, description: 'Filter by Category ID (via subCategory)' },
        { name: 'subCategoryId', in: 'query', schema: { type: 'string', format: 'uuid' } },
        { name: 'metalType', in: 'query', schema: { type: 'string' } },
        { name: 'purity', in: 'query', schema: { type: 'string' } },
        { name: 'search', in: 'query', schema: { type: 'string' } },
        { name: 'isActive', in: 'query', schema: { type: 'boolean' } },
        { name: 'sortBy', in: 'query', schema: { type: 'string', enum: ['createdAt', 'sku', 'name', 'grossWeight', 'netWeight'] } },
        { name: 'sortOrder', in: 'query', schema: { type: 'string', enum: ['asc', 'desc'] } },
        { name: 'page', in: 'query', schema: { type: 'integer', default: 1 } },
        { name: 'limit', in: 'query', schema: { type: 'integer', default: 10 } },
      ],
      responses: { 200: { description: 'Success' } },
    },
  },
  '/products/{id}': {
    get: { summary: 'Get Product by ID', tags: ['Products'], security: [{ bearerAuth: [] }], responses: { 200: { description: 'Success' } } },
    put: { summary: 'Update Product', tags: ['Products'], security: [{ bearerAuth: [] }], responses: { 200: { description: 'Success' } } },
    delete: { summary: 'Delete Product', tags: ['Products'], security: [{ bearerAuth: [] }], responses: { 200: { description: 'Success' } } },
  },
};
